Build: Use LDFLAGS variable from env and add -pthread flag
Without this change and error on linkage is displayed :

  ld: observer.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
  libpthread.so.0: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status

Also YOCTOLDFLAGS are replaced with regular LDFLAGS,
to use quality check.

Without this, QA check is failing and this message is reported:

  do_package_qa: QA Issue: No GNU_HASH in the elf binary:

Change-Id: I2f73b1c09908be38a9053943a894832519312751
Bug: https://jira.iotivity.org/browse/IOT-1111
Origin: https://github.com/TizenTeam/meta-oic
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>